FROM node:20.19.4-slim

RUN apt update && \
    apt install -y curl && \
    npm install -g nodemon

COPY start.sh /
RUN chmod +x /start.sh

USER node

WORKDIR /home/node/app

COPY package.json package-lock.json ./
# RUN npm ci

EXPOSE 8080

CMD [ "/start.sh" ]
